### ISSUE TITLE
blob exception on login 

### ISSUE THREAD

**Issue by mostafaasadi** [kiwiz/gkeepapi#28] opened 2018-06-13 01:47 UTC
Hi 
I have this : 
```
keep = gkeepapi.Keep()
try:
    keep.login(GAppUser, GAppPass)
except Exception as e:
    print(e)
```
and get this : 
```
'blob'
```
what does it mean ? and why ?
thank you :rose:

**Comment by kiwiz** [comment] 2018-06-19 04:12
Hi, can you provide more details on this exception. Also, please make sure you're using the newest version of the library.

**Comment by mostafaasadi** [comment] 2018-06-19 07:55
Hi
I installed last version from pip
and how i provide more details for you ?

**Comment by kiwiz** [comment] 2018-06-27 02:54
Does this happen with other accounts? If you remove the `try` `catch`, what stack trace do you get? (Please sanitize any credentials).

**Comment by mostafaasadi** [comment] 2018-06-27 07:00
```
keep = gkeepapi.Keep()
keep.login(GAppUser, GAppPass)
```
```
Traceback (most recent call last):
  File "keepbot.py", line 24, in <module>
    keep.login(GAppUser, GAppPass)
  File "/usr/local/lib/python3.5/dist-packages/gkeepapi/__init__.py", line 404, in login
    self.load(auth)
  File "/usr/local/lib/python3.5/dist-packages/gkeepapi/__init__.py", line 418, in load
    self.sync(True)
  File "/usr/local/lib/python3.5/dist-packages/gkeepapi/__init__.py", line 643, in sync
    self._parseNodes(changes['nodes'])
  File "/usr/local/lib/python3.5/dist-packages/gkeepapi/__init__.py", line 670, in _parseNodes
    node = _node.from_json(raw_node)
  File "/usr/local/lib/python3.5/dist-packages/gkeepapi/node.py", line 1421, in from_json
    node.load(raw)
  File "/usr/local/lib/python3.5/dist-packages/gkeepapi/node.py", line 1321, in load
    self.blob = self.from_json(raw['blob'])
KeyError: 'blob'
```

**Comment by kiwiz** [comment] 2018-06-28 05:33
Hi, that stack trace doesn't seem to match up with the current library. Can you make sure `gkeepapi` is up to date and then post a new stack trace?

**Comment by mostafaasadi** [comment] 2018-06-28 07:53
I upgraded to 0.10.9
```
➜  ~ sudo pip3 show gkeepapi
Name: gkeepapi
Version: 0.10.9
Summary: An unofficial Google Keep API client
Home-page: https://github.com/kiwiz/gkeepapi
Author: Kai
Author-email: z@kwi.li
License: MIT
Location: /usr/local/lib/python3.5/dist-packages
Requires: six, gpsoauth
Required-by:
```

```
Traceback (most recent call last):
  File "keepbot.py", line 24, in <module>
    keep.login(GAppUser, GAppPass)
  File "/usr/local/lib/python3.5/dist-packages/gkeepapi/__init__.py", line 404, in login 
    self.load(auth)
  File "/usr/local/lib/python3.5/dist-packages/gkeepapi/__init__.py", line 418, in load
    self.sync(True) 
  File "/usr/local/lib/python3.5/dist-packages/gkeepapi/__init__.py", line 645, in sync
    self._parseNodes(changes['nodes'])
  File "/usr/local/lib/python3.5/dist-packages/gkeepapi/__init__.py", line 672, in _parseNodes
    node = _node.from_json(raw_node)
  File "/usr/local/lib/python3.5/dist-packages/gkeepapi/node.py", line 1450, in from_json
    node.load(raw)
  File "/usr/local/lib/python3.5/dist-packages/gkeepapi/node.py", line 1350, in load
    self.blob = self.from_json(raw['blob'])
KeyError: 'blob'

```

**Comment by kiwiz** [comment] 2018-07-11 00:19
@layolu Thanks for the detailed investigation work.

I've pushed up 0.10.10 that should fix this issue. @mostafaasadi

**Comment by layolu** [comment] 2018-07-11 08:51
I upgraded gkeepapi to 0.10.10 and the issue is fixed in my environment. Thanks @kiwiz !

**Closed** 2018-07-21 02:11 UTC
