### ISSUE TITLE
Parse error in <class 'gkeepapi.node.WebLink'>

### ISSUE THREAD

**Issue by github-of-wone** [kiwiz/gkeepapi#155] opened 2023-12-26 18:57 UTC
Please make sure you've done the following before submitting your issue:

- [ ] Check that you're running the newest version of the library.
- [ ] If you're providing a stack trace, make sure it doesn't contain your password.
- [ ] If you're getting a KeyError or ParseException, please follow the instructions [here](https://gkeepapi.readthedocs.io/en/latest/#reporting-errors) to dump the raw data.

Additionally, please provide the following information:

- Operating system - Windows 11
- Python version - 3.11.4

{'webLink': {'kind': 'notes#webLink', 'url': 'https://support.google.com/keep/?p=migrated_from_assistant', 'provenanceUrl': 'https://support.google.com/keep/?p=migrated_from_assistant', 'hasThumbnailUrl': True}}

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\node.py:214](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py:214), in Element.load(self, raw)
    [213](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=212) try:
--> [214](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=213)     self._load(raw)
    [215](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=214) except (KeyError, ValueError) as e:

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\node.py:291](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py:291), in WebLink._load(self, raw)
    [290](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=289) super(WebLink, self)._load(raw)
--> [291](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=290) self._title = raw['webLink']['title']
    [292](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=291) self._url = raw['webLink']['url']

KeyError: 'title'

The above exception was the direct cause of the following exception:

ParseException                            Traceback (most recent call last)
[d:\Cloud\OneDrive\Projects\Python\GoogleKeep\gkeep_desktopper.pyw](file:///D:/Cloud/OneDrive/Projects/Python/GoogleKeep/gkeep_desktopper.pyw) in line 16
     [14](file:///d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/gkeep_desktopper.pyw?line=13) keep = gkeepapi.Keep()
     [15](file:///d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/gkeep_desktopper.pyw?line=14) # success = keep.login('user@gmail.com', 'password')
---> [16](file:///d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/gkeep_desktopper.pyw?line=15) success = keep.login(login1, pw1)
     [20](file:///d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/gkeep_desktopper.pyw?line=19) note = keep.createNote('Todo', 'Eat breakfast')
     [21](file:///d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/gkeep_desktopper.pyw?line=20) note.pinned = True

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\__init__.py:699](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py:699), in Keep.login(self, email, password, state, sync, device_id)
    [697](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=696) ret = auth.login(email, password, device_id)
    [698](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=697) if ret:
--> [699](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=698)     self.load(auth, state, sync)
    [701](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=700) return ret

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\__init__.py:749](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py:749), in Keep.load(self, auth, state, sync)
    [747](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=746)     self.restore(state)
    [748](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=747) if sync:
--> [749](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=748)     self.sync(True)

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\__init__.py:1024](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py:1024), in Keep.sync(self, resync)
   [1021](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=1020)     self._clear()
   [1023](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=1022) # self._sync_reminders(resync)
-> [1024](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=1023) self._sync_notes(resync)
   [1026](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=1025) if _node.DEBUG:
   [1027](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=1026)     self._clean()

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\__init__.py:1074](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py:1074), in Keep._sync_notes(self, resync)
   [1072](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=1071) # Hydrate notes and any children.
   [1073](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=1072) if "nodes" in changes:
-> [1074](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=1073)     self._parseNodes(changes["nodes"])
   [1076](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=1075) self._keep_version = changes["toVersion"]
   [1077](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=1076) logger.debug("Finishing sync: %s", self._keep_version)

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\__init__.py:1110](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py:1110), in Keep._parseNodes(self, raw)
   [1106](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=1105)         deleted_nodes.append(node)
   [1108](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=1107) else:
   [1109](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=1108)     # Otherwise, this is a new node. Attempt to hydrate it.
-> [1110](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=1109)     node = _node.from_json(raw_node)
   [1111](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=1110)     if node is None:
   [1112](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/__init__.py?line=1111)         logger.debug("Discarded unknown node")

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\node.py:1930](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py:1930), in from_json(raw)
   [1928](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=1927)     return None
   [1929](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=1928) node = ncls()
-> [1930](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=1929) node.load(raw)
   [1932](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=1931) return node

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\node.py:214](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py:214), in Element.load(self, raw)
    [206](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=205) """Unserialize from raw representation. (Wrapper)
    [207](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=206) 
    [208](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=207) Args:
   (...)
    [211](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=210)     ParseException: If there was an error parsing data.
    [212](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=211) """
    [213](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=212) try:
--> [214](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=213)     self._load(raw)
    [215](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=214) except (KeyError, ValueError) as e:
    [216](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=215)     raise_from(exception.ParseException('Parse error in %s' % (type(self)), raw), e)

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\node.py:1191](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py:1191), in TopLevelNode._load(self, raw)
   [1190](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=1189) def _load(self, raw):
-> [1191](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=1190)     super(TopLevelNode, self)._load(raw)
   [1192](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=1191)     self._color = ColorValue(raw['color']) if 'color' in raw else ColorValue.White
   [1193](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=1192)     self._archived = raw['isArchived'] if 'isArchived' in raw else False

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\node.py:1046](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py:1046), in Node._load(self, raw)
   [1044](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=1043) self.timestamps.load(raw['timestamps'])
   [1045](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=1044) self.settings.load(raw['nodeSettings'])
-> [1046](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=1045) self.annotations.load(raw['annotationsGroup'])

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\node.py:214](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py:214), in Element.load(self, raw)
    [206](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=205) """Unserialize from raw representation. (Wrapper)
    [207](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=206) 
    [208](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=207) Args:
   (...)
    [211](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=210)     ParseException: If there was an error parsing data.
    [212](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=211) """
    [213](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=212) try:
--> [214](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=213)     self._load(raw)
    [215](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=214) except (KeyError, ValueError) as e:
    [216](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=215)     raise_from(exception.ParseException('Parse error in %s' % (type(self)), raw), e)

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\node.py:524](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py:524), in NodeAnnotations._load(self, raw)
    [521](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=520)     return
    [523](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=522) for raw_annotation in raw['annotations']:
--> [524](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=523)     annotation = self.from_json(raw_annotation)
    [525](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=524)     self._annotations[annotation.id] = annotation

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\node.py:505](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py:505), in NodeAnnotations.from_json(cls, raw)
    [503](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=502)     return None
    [504](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=503) annotation = bcls()
--> [505](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=504) annotation.load(raw)
    [507](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=506) return annotation

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\node.py:214](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py:214), in Element.load(self, raw)
    [206](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=205) """Unserialize from raw representation. (Wrapper)
    [207](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=206) 
    [208](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=207) Args:
   (...)
    [211](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=210)     ParseException: If there was an error parsing data.
    [212](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=211) """
    [213](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=212) try:
--> [214](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=213)     self._load(raw)
    [215](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=214) except (KeyError, ValueError) as e:
    [216](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=215)     raise_from(exception.ParseException('Parse error in %s' % (type(self)), raw), e)

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\node.py:450](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py:450), in Context._load(self, raw)
    [448](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=447) self._entries = {}
    [449](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=448) for key, entry in raw.get('context', {}).items():
--> [450](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=449)     self._entries[key] = NodeAnnotations.from_json({key: entry})

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\node.py:505](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py:505), in NodeAnnotations.from_json(cls, raw)
    [503](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=502)     return None
    [504](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=503) annotation = bcls()
--> [505](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=504) annotation.load(raw)
    [507](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=506) return annotation

File [~\AppData\Roaming\Python\Python311\site-packages\gkeepapi\node.py:216](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py:216), in Element.load(self, raw)
    [214](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=213)     self._load(raw)
    [215](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=214) except (KeyError, ValueError) as e:
--> [216](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/gkeepapi/node.py?line=215)     raise_from(exception.ParseException('Parse error in %s' % (type(self)), raw), e)

File [~\AppData\Roaming\Python\Python311\site-packages\future\utils\__init__.py:406](https://file+.vscode-resource.vscode-cdn.net/d%3A/Cloud/OneDrive/Projects/Python/GoogleKeep/~/AppData/Roaming/Python/Python311/site-packages/future/utils/__init__.py:406), in raise_from(exc, cause)
    [404](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/future/utils/__init__.py?line=403) myglobals['__python_future_raise_from_cause'] = cause
    [405](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/future/utils/__init__.py?line=404) execstr = "raise __python_future_raise_from_exc from __python_future_raise_from_cause"
--> [406](file:///c%3A/Users/samir/AppData/Roaming/Python/Python311/site-packages/future/utils/__init__.py?line=405) exec(execstr, myglobals, mylocals)

File <string>:1

ParseException: Parse error in <class 'gkeepapi.node.WebLink'>

**Comment by csimpf** [comment] 2023-12-27 01:51
I hit this recently too. Are you using the latest version? 0.15.1.

**Comment by TheGreatestAlan** [comment] 2023-12-27 18:14
Yeah, so if this is the same thing that I was looking at, the issue is how this code is attempting to load weblinks.  

Basically if it identifies a WebLink in the code, it assumes that there must be a title and description.  Those values don't necessarily always exist anymore.  The case is that now looks like google is adding a source in certain cases that looks something like "migrated by google assistant" or something like that in google keep.  This source is being interpreted as a weblink.  These objects do not have the expected title and descriptions, and so are throwing a parse exception all the way out.   I was able to sidestep this by removing that source from all my notes.  But a fix is a little larger than I have time for to PR the code base.

Hope this helps anyone that runs into this.

**Comment by kiwiz** [comment] 2023-12-27 20:05
Should've been resolved as of `0.15.1` (#153) - are you running the latest version?

**Comment by csimpf** [comment] 2023-12-27 23:31
To elaborate on @TheGreatestAlan's comment (and perhaps this belongs in a separate issue)

A number of my Google Keep notes recently had a "Moved from Google Assistant" tag on them. Logging into Keep and Manually deleting these fixed gkeepapi for me.

**Comment by github-of-wone** [comment] 2023-12-28 10:39
> Should've been resolved as of `0.15.1` (#153) - are you running the latest version?

Yes, still not working!

**Comment by kiwiz** [comment] 2023-12-28 23:59
```
 --> 291 self._title = raw['webLink']['title']
```
This code from the stack trace no longer exists on `0.15.1`

**Comment by github-of-wone** [comment] 2023-12-29 05:22
DOn;t understand what is to be done.  Please can you update the version and let me know.  Thanks.

**Comment by github-of-wone** [comment] 2023-12-30 07:28
Plz can someone revert !

**Comment by github-of-wone** [comment] 2024-01-04 06:16
Plz can someone revert on this!

**Comment by kiwiz** [comment] 2024-01-05 21:51
@github-of-wone The issue is fixed in the newest version of the library (`0.15.1`). Your stack trace indicates you are not running the latest version, so upgrading will resolve the issue for you.

**Comment by github-of-wone** [comment] 2024-01-06 03:27
@kiwiz thanks for the above but
```
---------------------------------------------------------------------------
LoginException                            Traceback (most recent call last)
Cell In[61], [line 4](vscode-notebook-cell:?execution_count=61&line=4)
      [1](vscode-notebook-cell:?execution_count=61&line=1) # %%
      [2](vscode-notebook-cell:?execution_count=61&line=2) from loginpw import login1, pw1
----> [4](vscode-notebook-cell:?execution_count=61&line=4) keep.login(
      [5](vscode-notebook-cell:?execution_count=61&line=5)     login1, pw1
      [6](vscode-notebook-cell:?execution_count=61&line=6) )  # , "xyz")  
      [8](vscode-notebook-cell:?execution_count=61&line=8) gnotes = keep.all()

File [c:\pi\python312\Lib\site-packages\gkeepapi\__init__.py:703](file:///C:/pi/python312/Lib/site-packages/gkeepapi/__init__.py:703), in Keep.login(self, email, password, state, sync, device_id)
    [700](file:///c%3A/pi/python312/Lib/site-packages/gkeepapi/__init__.py?line=699) if device_id is None:
    [701](file:///c%3A/pi/python312/Lib/site-packages/gkeepapi/__init__.py?line=700)     device_id = f"{get_mac():x}"
--> [703](file:///c%3A/pi/python312/Lib/site-packages/gkeepapi/__init__.py?line=702) auth.login(email, password, device_id)
    [704](file:///c%3A/pi/python312/Lib/site-packages/gkeepapi/__init__.py?line=703) self.load(auth, state, sync)

File [c:\pi\python312\Lib\site-packages\gkeepapi\__init__.py:58](file:///C:/pi/python312/Lib/site-packages/gkeepapi/__init__.py:58), in APIAuth.login(self, email, password, device_id)
     [56](file:///c%3A/pi/python312/Lib/site-packages/gkeepapi/__init__.py?line=55) # Bail if no token was returned.
     [57](file:///c%3A/pi/python312/Lib/site-packages/gkeepapi/__init__.py?line=56) if "Token" not in res:
---> [58](file:///c%3A/pi/python312/Lib/site-packages/gkeepapi/__init__.py?line=57)     raise exception.LoginException(res.get("Error"), res.get("ErrorDetail"))
     [60](file:///c%3A/pi/python312/Lib/site-packages/gkeepapi/__init__.py?line=59) self._master_token = res["Token"]
     [62](file:///c%3A/pi/python312/Lib/site-packages/gkeepapi/__init__.py?line=61) # Obtain an OAuth token.

LoginException: ('BadAuthentication', None)
```
:-(

**Comment by TheGreatestAlan** [comment] 2024-01-06 17:42
@kiwiz yup that should do it.  Your changes are similar to the ones I made.  I've updated my version, but don't really have a way to test it because I don't know how to create a note that google assistant migrated.

Thanks for the work again

**Comment by djsudduth** [comment] 2024-01-12 18:15
What actually changed here - all of the backward compatible libraries have this error now. Was this a Google change?

**Comment by kiwiz** [comment] 2024-01-12 22:53
See this issue for details: https://github.com/simon-weber/gpsoauth/issues/48

An alternative mechanism for authenticating has been merged into `gpsoauth` (per https://github.com/kiwiz/gkeepapi/issues/137). Once a new release is made, I can bump the dependency in `gkeepapi`.

**Comment by kiwiz** [comment] 2024-01-19 19:26
Closing this in favor of #81

**Closed by kiwiz** 2024-01-19 19:26 UTC
