### ISSUE TITLE
KeyError: "checked" when trying to sync new checkbox in list

### ISSUE THREAD

**Issue by danielwossenu** [kiwiz/gkeepapi#19] opened 2018-03-18 15:19 UTC
I'm getting a checkbox list from my Google Keep and assigning it to glist, adding a checked checkbox item and trying to sync. That code is:

```
glist = keep.get("*********")
glist.add('Item 3', True)
keep.sync()
```

I get the following error:

```
File "lib\site-packages\gkeepapi\node.py", line 1176, in load
self._checked = raw['checked']
KeyError: 'checked'
```

I poked around and it looks like when when line 559 in __init__.py is run, the variable "changes" is assigned with the checkbox not having a "checked" property. Here is line 559:

```
changes = self._keep_api.changes(
                target_version=self._version,
                nodes=[i.save() for i in self._findDirtyNodes()],
                labels=[i.save() for i in self._labels.values()] if labels_updated else None,
            )
```

if I stop right before that code is run and run the param snippet from above: 
`nodes=[i.save() for i in self._findDirtyNodes()]` 
you can see that the new ListItem has a property "checked = True".

Stepping through line 559 in __init__.py takes you to line 269 in __init__.py, it's the return for the `self._keep_api.changes()` function:

```
return self.send(
            url=self._base_url + 'changes',
            method='POST',
            json=params
```

The response you get from self.send() does not have the "checked" property anymore. It does have a "checked_ts_micro" property with a value of `u'1521385638051000'`. It looks like some measure of when the box was checked. If I run the original code with the checked param as False, `glist.add('Item 3', False)` ,that "checked_ts_micro" property has a value of  `u'0'`.

This is as far as I gotten with investigating it. Not sure why it doesn't return a "checked" property but it might be an easy fix to just add something like:

```
if: checked_ts_micro > 0:
    self.checked  = True
else:
    self.checked  = False
```

**Comment by danielwossenu** [comment] 2018-03-19 15:15
After further investigation, it looks like this happens when there is a merge conflict between the local note and the server note. There looks to be no difference for my specific case so not sure why it's displaying this. You can see in the response from the server at line 269 in __init__.py the new list item is returned with a property called "mergeConflict".

**Comment by danielwossenu** [comment] 2018-03-19 15:21
This could be because the newest update of this repo sets the baseVersion to a default number if it's not found. The server might be using baseVersion to determine if there is a merge conflict

**Comment by kiwiz** [comment] 2018-03-21 05:42
Nice find! I've never experienced a merge conflict on the frontend, so I don't know how Keep lets you manage that. Also, not sure if `gkeepapi` should. Maybe it's best to throw an exception and let the user handle it.

**Comment by kiwiz** [comment] 2018-03-21 05:44
(To clarify, I do intend to fix the current issue with `baseVersion`)

**Comment by kiwiz** [comment] 2018-03-25 05:07
@danielwossenu Can you check if this is fixed now? ^

**Comment by danielwossenu** [comment] 2018-03-25 22:36
It still does not work, but now it raises a merge exception

**Comment by kiwiz** [comment] 2018-03-26 01:18
@danielwossenu Finally managed to reproduce it. Hopefully the above change should fix the issue!

**Comment by newbeb** [comment] 2018-03-31 21:27
It works for me now, with the following code, which was failing before the [a933808 ](https://github.com/kiwiz/gkeepapi/commit/a93380809c447fed81c27e2b17a8af944b758464 )patch.

```python
import gkeepapi as gkeepapi

keep = gkeepapi.Keep()
keep.login("someone", "password")

glist = keep.createList('Test List2', [('T1', False), ('T2', True)])
keep.sync()
```

**Comment by newbeb** [comment] 2018-04-01 01:13
There is a bug in the load(self, raw) function in node.py where a string is getting loaded into _version and then comparison is failing due to "TypeError: unorderable types: str() > int()" on line 872 of node.py

The value of _version is loaded from the JSON as a str if the baseVersion is present

```python
self._version = raw['baseVersion'] if 'baseVersion' in raw else self._version
```

Which throws the "TypeError: unorderable types: str() > int()" in the save function

```python
if not self.moved and self._version > 0:
```

I'll do a pull request shortly.

**Closed** 2018-04-17 15:50 UTC
Labels: bug
