### ISSUE TITLE
ParseException thrown

### ISSUE THREAD

**Issue by ItsMates** [kiwiz/gkeepapi#45] opened 2018-09-22 13:42 UTC
Throws during login() and also during sync()

{u'drawingId': u'1u6s3cJm8s_JN14haU91d64nEW8GW-eVfbQ', u'snapshotData': {u'mimet
ype': u'image/png', u'kind': u'notes#blob', u'is_uploaded': True, u'byte_size':
107215, u'height': 2048, u'width': 1396, u'extracted_text': u'N\xe1sleduj\xed ro
zvrh popisuje podrobn\u011b Po "T Rok\xe1tio-Radys - \xfatisi.\xf6\xf6ing Tai.zo
isit - n Doma3ominio Stooo TEi i .solind.in noiooDoma cr- Volno ""\' . " ""nazor
........zo 15.oo Indiu K\u010d 18:30 p\xe1- Tootnoo 19:15 Doma Eidiv practisei N
et', u'type': u'IMAGE', u'extraction_status': u'FAILED'}, u'snapshotProtoFprint'
: u'9356325366218173475', u'snapshotFingerprint': u'-9090418707491378141', u'ink
Hash': u'945657ddd2b534cd'}

    import gkeepapi

    def main():
        keep = gkeepapi.Keep()
        
        try: 
            success = keep.login('...', '...')
        except gkeepapi.exception.ParseException as e:
            print(e.raw) 
        
        note = keep.createNote('Todo', 'Eat breakfast')
        note.pinned = False
        note.color = gkeepapi.node.ColorValue.Red
        
        try: 
            keep.sync()
        except gkeepapi.exception.ParseException as e:
            print(e.raw)
            

    if __name__ == "__main__":
        main()

**Comment by kiwiz** [comment] 2018-09-22 14:49
@ItsMates Your stack trace looked like it had creds. Please change your password asap, if so.

**Comment by kiwiz** [comment] 2018-09-22 14:55
Dupe of #44.

**Closed by kiwiz** 2018-09-22 14:55 UTC

**Comment by ItsMates** [comment] 2018-09-22 15:10
Oh snap! Thanks, I looked and thought it's creds free.. Password changed. Sorry for the dupe of #44. I really like your project, good work guys!
