### ISSUE TITLE
Loggin issue with AppPassword

### ISSUE THREAD

**Issue by rhalaly** [kiwiz/gkeepapi#144] opened 2023-06-27 08:51 UTC
I'm using Windows 11 and Python 3.7. I have Google account with 2-Step authentication, so I generated AppPassword. But when I use it I still get

```
gkeepapi.LoginException: ('NeedsBrowser', 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.')
```

What can I do further? I already created an AppPassword named `gkeepapi` but it still not working...

**Comment by jkitching** [comment] 2023-08-25 04:00
I encountered this error running an old version of gpsoauth.  Looks like the fix was published in gpsoauth==1.0.1:

https://github.com/simon-weber/gpsoauth/issues/37

**Comment by Cris70** [comment] 2023-10-18 09:40
I am using gpsoauth 1.0.3 and I have the same issue.

Here is my config:
- python 3.11.5
- future==0.18.3
- gkeepapi==0.15.0
- gpsoauth==1.0.3
- pycryptodomex==3.19.0
- requests==2.31.0

**Comment by jalukii** [comment] 2023-11-29 05:22
I am facing the same problem, but it is more strange. Yesterday, when I started implementing my thing with `gkeepapi`, I got ``gkeepapi.exception.BrowserLoginRequiredException: https://accounts.google.com/signin/continue?sarp=1&scc=1&continue=https://accounts.google.com/o/android/auth?hl%3Den_us%26xoauth_display_name%3DAndroid%2BLogin%2BService%26source%3DAndroid%2BLogin&plt=...``` 

Strangely enough, it suddenly started working, so I finished my thing. Today I woke up, ran my script and it broke again. Same error, but the same configuration. Are there some Google changes? Or where can be the problem?

**Comment by vojtechmarek-dev** [comment] 2023-12-07 11:07
Hi I am having same problem with trying to login to Gkeep via app password i get
`gkeepapi.exception.BrowserLoginRequiredException`

is there a solution for this?

**Comment by robin-pham** [comment] 2023-12-08 09:40
Same, ran into this issue yesterday as well

**Comment by derekantrican** [comment] 2023-12-14 02:03
Just started seeing this after the new keep update (#153). My code was working fine until I pulled the latest version of the gkeepapi library, then I started seeing this issue. I'm also using an app password on a 2FA account like a few others here

**Comment by flecmart** [comment] 2023-12-15 13:49
Hey, 

I am also currently trying to resolve this for my own project and I just leave my findings and thoughts here - maybe they help someone.

The only combination of requirements that still works for me is:

```
urllib3<2
gpsoauth==1.0.2
gkeepapi==0.14.2
```

Additionaly you need to have openssl version 1 on OS level. I achieve this for example by using `python:3.11-bullseye` image for docker.

As soon as you upgrade your openssl version you will get `Bad Authentication` exception and as soon as I upgrade gpsoauth to a more recent version I get exactly the same behavior that  you are describing in this issue.

@kiwiz 
What environment are you developing/testing on? I would like to bump gkeepapi and gpsoauth but I cannot get it to work and I am out of ideas at this moment.

**Comment by rchampion** [comment] 2023-12-17 04:11
I can't seem to get any combination of python versions or requirements to login. Hoping a solution is presented soon!

**Comment by robin-pham** [comment] 2023-12-17 05:05
I gave up completely on using Google Keep, as this authentication method seems to break every other year or so. If anyone was using this library for personal reasons I recommend something with actual official/OAuth support like Google Tasks (though who knows how long Google will _keep_ this around either 😂).

**Comment by derekantrican** [comment] 2023-12-17 06:27
I would love to move to something else, but I use this library because Google Assistant has moved to exclusively using Keep for notes & lists (I use the "Note to Self" option a lot). They used to provide the option to set your own notes app, but they took that away. So now I use this library to mirror my notes to my email.

**Comment by robin-pham** [comment] 2023-12-17 10:53
Yeah that's exactly why I was using this library as well, for Google Assistant! I found out that if you use the "Add task" command, it adds to Google Tasks, so I no longer have to use note to self or add to my todo list/shopping list and no longer have to deal with Google Keep.

**Comment by rchampion** [comment] 2023-12-17 18:53
> I would love to move to something else, but I use this library because Google Assistant has moved to exclusively using Keep for notes & lists (I use the "Note to Self" command a lot). They used to provide the option to set your own notes app, but they took that away. So now I use this library to mirror my notes to my email.

Same. I have a script that takes Keep Notes and puts them in a bullet point list in Notion for me. Then I have GA devices all over my house, my watch, and my phone so I can voice note from anywhere. This API is literally the only way to accomplish this core part of my day to day.

**Comment by robin-pham** [comment] 2023-12-18 04:28
Funny that we've all been using this library for a similar purpose, i.e. Google Assistant devices -> Make a Keep note with voice -> Sync to some other service.

Just FYI, I succesfully migrated my flow to Google Tasks, since it has an API officially supported by Google and has an easy OAuth method to manage personal auth, and their underlying model/API is very similar to Keep. Basically the same voice command except instead of "note to self"/"add to todo", it's "Add Task ___".

**Comment by viertel97** [comment] 2023-12-18 09:19
> Just FYI, I succesfully migrated my flow to Google Tasks, since it has an API officially supported by Google and has an easy OAuth method to manage personal auth, and their underlying model/API is very similar to Keep. Basically the same voice command except instead of "note to self"/"add to todo", it's "Add Task ___".

Could you elaborate that a little bit? (Not sure if this is the right place for it) Does it also have the same functionality regarding different lists? Eg. Add Task to List "Shopping List" or "ToDo-List"? And do you have a source regarding using the API via Python?

**Comment by robin-pham** [comment] 2023-12-18 23:50
> Could you elaborate that a little bit? 

[Python quickstart guide + code](https://developers.google.com/tasks/quickstart/python#configure_the_sample). 

^ has the instructions on how to get an app running. You do need a Google Cloud project, but the API itself costs nothing so I haven't been getting charged. Basically I have a background worker script that polls Tasks, once it sees a new one, mirrors the tasks in my other service, then deletes the Task so I don't get reminders.


> Does it also have the same functionality regarding different lists? Eg. Add Task to List "Shopping List" or "ToDo-List"? 


The Tasks app itself has different lists, but the voice commands don't work with being able to add to a specific list, it'll always add tasks to the default list sadly.

**Comment by derekantrican** [comment] 2023-12-19 00:36
For me, the "Add a task" flow always gives a second prompt of "When do you want to be reminded?". So it's not really a drop-in replacement

**Comment by derekantrican** [comment] 2023-12-22 01:56
I just my original code working and wanted to share the solution. This is similar to @flecmart 's post above and I got it from a consumer of this project: https://github.com/djsudduth/keep-it-markdown/issues/72

I ran the following:
- `pip install urllib3==1.25.1`
- `pip install gpsoauth==1.0.2`

After this, my original code worked with the latest version of gkeepapi

**Comment by viertel97** [comment] 2023-12-22 11:03
> I just my original code working and wanted to share the solution. This is similar to @flecmart 's post above and I got it from a consumer of this project: [djsudduth/keep-it-markdown#72](https://github.com/djsudduth/keep-it-markdown/issues/72)
> 
> I ran the following:
> 
> * `pip install urllib3==1.25.1`
> * `pip install gpsoauth==1.0.2`
> 
> After this, my original code worked with the latest version of gkeepapi

I can confirm this!
I used that https://github.com/djsudduth/keep-it-markdown/issues/72#issuecomment-1793495242 code to gather the master token and then could login with `keep.resume(GOOGLE_MAIL, TOKEN)` and the following dependencies:
```
gpsoauth==1.0.4
gkeepapi==0.15.1
```

**Comment by csimpf** [comment] 2023-12-27 23:39
Hey @derekantrican @viertel97 I attempted those steps but was still getting the same `BrowserLoginRequiredException` I was getting with `gkeepapi` and wasn't able to get further. Do you have any pointers for this?

(Either way - I was able to keep using my existing version of `gkeepapi`; `v0.14.2` by deleting tags from my notes as per https://github.com/kiwiz/gkeepapi/issues/155#issuecomment-1870691191)

**Comment by Cris70** [comment] 2023-12-28 14:57
> > I just my original code working and wanted to share the solution. This is similar to @flecmart 's post above and I got it from a consumer of this project: [djsudduth/keep-it-markdown#72](https://github.com/djsudduth/keep-it-markdown/issues/72)
> > I ran the following:
> > 
> > * `pip install urllib3==1.25.1`
> > * `pip install gpsoauth==1.0.2`
> > 
> > After this, my original code worked with the latest version of gkeepapi
> 
> I can confirm this! I used that [djsudduth/keep-it-markdown#72 (comment)](https://github.com/djsudduth/keep-it-markdown/issues/72#issuecomment-1793495242) code to gather the master token and then could login with `keep.resume(GOOGLE_MAIL, TOKEN)` and the following dependencies:
> 
> ```
> gpsoauth==1.0.4
> gkeepapi==0.15.1
> ```

Worked for me too!!!
Thank you!

**Comment by kiwiz** [comment] 2024-01-19 19:29
Closing in favor of #81

**Closed by kiwiz** 2024-01-19 19:29 UTC
